### ISSUE TITLE
Login?

### ISSUE THREAD

**Issue by imobiledev** [tngoman/Store-POS#11]
Hi, what is the cypher key to open the DB files? And what is the login for admin?

thanks

**Comment by doosom** [comment]
default password is admin

**Comment by tngoman** [comment]
Hi,

Yes, the default username and password is admin. Just updated readme

There is no cypher key to open the DB files

**Comment by imobiledev** [comment]
Thanks guys! I'm founder and CEO of www.paybyface.io I would like to talk to you about a partnership opportunity. Please email me directly mihai@paybyface.io

**Comment by tngoman** [comment]
Thank you guys for showing interest in the project.
