### ISSUE TITLE
Product images are not saved

### ISSUE THREAD

**Issue by doosom** [tngoman/Store-POS#12]
When adding a product image to a new product I can see the db being updated with a filename but on the console I get the following error:

(node:2618) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

Using Node v12.18.1 on a Linux system.

I suppose the issue is multer or express-fileupload but I never worked with them thus I'm not sure where to look for the code that uses the Buffer().

**Comment by tngoman** [comment]
Hi, sorry I forgot to get back to you.

Did you manage to resolve this?
