### ISSUE TITLE
Can't run app

### ISSUE THREAD

**Issue by ntphong1990** [tngoman/Store-POS#14]
<img width="531" alt="Screen Shot 2020-08-25 at 13 58 03" src="https://user-images.githubusercontent.com/14165753/91142558-2c14ac00-e6db-11ea-93e5-26724a3e846b.png">
<img width="433" alt="Screen Shot 2020-08-25 at 13 58 22" src="https://user-images.githubusercontent.com/14165753/91142563-2fa83300-e6db-11ea-85e4-97f9380a5b45.png">

I just start project by run "npm run electron" and get this error, the app seem not work

**Comment by tngoman** [comment]
Hi, did you run npm install first?

**Comment by ntphong1990** [comment]
@tngoman sure man

**Comment by tngoman** [comment]
It just seems like that would only happen if electron is not installed, 
but the issue is may be related to this: https://github.com/electron/electron/issues/21408. 
I have not been able to reproduce the error on my side.

**Comment by stuhlpfarrer** [comment]
Had the same issue, you have to enable the remote module in start.js like so:

```
function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1500,
    height: 1200,
    frame: true,
    minWidth: 1200,
    minHeight: 750,
    webPreferences: {
      nodeIntegration: true,
      enableRemoteModule: true           <----
    },
  });
```
