### ISSUE TITLE
incorrect username or password

### ISSUE THREAD

**Issue by nnamdei** [tngoman/Store-POS#4]
I clone this project and built a new POS.exe file. I installed it but used the default admin (username and password) and i got a prompt that it is incorrect.

**Comment by tngoman** [comment]
Please check if those are the details in: AppData\Roaming\POS\config.json

**Comment by nnamdei** [comment]
Thanks for this info, i had to delete the folder from a previous installation done while testing. Nice Job.

Secondly, how can transactions be exported in csv or pdf format?

**Comment by tngoman** [comment]
Thanks.
Transactions use the jquery datatables library.
You could just add the extensions for export buttons needed.
Example: https://datatables.net/extensions/buttons/examples/html5/simple.html

**Comment by nnamdei** [comment]
I tried the implementation and it didnt work. Please could you help with a snippet to check out

**Comment by tngoman** [comment]
Here are much simpler ways to add export buttons: https://datatables.net/extensions/buttons/

MSI Installer guide: https://ourcodeworld.com/articles/read/927/how-to-create-a-msi-installer-in-windows-for-an-electron-framework-application

Standard installer exe: https://github.com/electron/windows-installer

You'd need to create an installer using either of the two methods above. All the resources will be packed inside the installer and that's what you would take to other computers.

**Comment by nnamdei** [comment]
Added the buttons and will continue with the build process for the exe file. Thanks for the support.
