### ISSUE TITLE
add barCode to addProduct

### ISSUE THREAD

**Issue by ailakhdar** [tngoman/Store-POS#9]
hey ive been trying to work on switching the app from automatic barcode generator ,to manual input and keeping generator , looks like im lost , 
if you can guid me ,to improve this part thank you

**Comment by tngoman** [comment]
Hi, the app receives the product ID as a parameter, then generates the barcode. 
When you say manually, do you mean you want to pass something else in?

This is the library used: https://lindell.me/JsBarcode/

**Comment by ailakhdar** [comment]
@tngoman yes i want to pass the acctual product codeBar and not the auto_generated by(Math/time) also add that on scan SKU

**Comment by tngoman** [comment]
The barcode is generated on the fly just before display on line 1516
You probably need to create an input field for entering the custom barcode in the product add form 
Then it would be the barcode that you pass in on line 1516

Before:  **$("#"+pro._id+"").JsBarcode(pro._id, {**       
After:  **$("#"+pro._id+"").JsBarcode(barcode, {**       

Then edit api/inventory.js line 140 
If your new field is called barcode then you'd replace _id with barcode.
Before:    **_id: parseInt(request.skuCode)**
After:  **barcode: parseInt(request.skuCode)**

This is the logic to use but you seem to understand this already. Do you need help with writing the actual code? 

You can send some code to be looked at to support@storepointofsale.com

Thanks
